## Description
This notebook demostrates how to connect to Open Data Cube and interrogate the available products and measurements stored within. Topic covered include:
* How to connect to a datacube
* How to list all products
* How to list a selected product's measurements
* How to interactively visualise data in the datacube

## Load packages
The datacube package is required to access and work with available data. The pandas package is required to format tables. The DcViewer utility will allow us to interactively explore the products available in the datacube.

In [1]:
import datacube
import pandas as pd
from odc.ui import DcViewer

# Set some configurations for displaying tables nicely
pd.set_option('display.max_colwidth', 200)
pd.set_option('display.max_rows', None)

## Connect to the datacube
Users need to specify a name for their session, known as the app name.

This name is generated by the user and is used to track down issues with database queries. It does not have any effect on the analysis.
The resulting dc object is what we use to access all the data contained within the datacube.

In [2]:
dc = datacube.Datacube(app='Sentinel_2')

## List products
Once a datacube instance has been created, users can explore the products and measurements stored within by using the dc.list_products().columns function.

In [3]:
dc.list_products().columns

products = dc.list_products()

display_columns = ["name",
                   "description",
                   "default_crs",
                   "default_resolution"]

products[display_columns].sort_index()

,name,description,default_crs,default_resolution
name,,,,
gm_s2_annual,gm_s2_annual,"Surface Reflectance Annual Geometric Median and Median Absolute Deviations, Sentinel-2",None,None
gm_s2_semiannual,gm_s2_semiannual,"Surface Reflectance Semiannual Geometric Median and Median Absolute Deviations, Sentinel-2",None,None
s2_l2a,s2_l2a,"Sentinel-2a and Sentinel-2b imagery, processed to Level 2A (Surface Reflectance) and converted to Cloud Optimized GeoTIFFs",None,None

## List measurements
Most products are associated with a range of available measurements. These can be individual satellite bands (e.g. Sentinel's near-infrared band) or statistical product summaries.

Using the name column of products listed above, let's interrogate the measurements associated with the Sentinal product using the dc.list_measurements() function.

In [4]:
product="s2_l2a"

measurements = dc.list_measurements()
measurements.loc[product]

,name,dtype,units,nodata,aliases,flags_definition
measurement,,,,,,
B01,B01,uint16,1,0.0,"[band_01, coastal_aerosol]",NaN
B02,B02,uint16,1,0.0,"[band_02, blue]",NaN
B03,B03,uint16,1,0.0,"[band_03, green]",NaN
B04,B04,uint16,1,0.0,"[band_04, red]",NaN
B05,B05,uint16,1,0.0,"[band_05, red_edge_1]",NaN
B06,B06,uint16,1,0.0,"[band_06, red_edge_2]",NaN
B07,B07,uint16,1,0.0,"[band_07, red_edge_3]",NaN
B08,B08,uint16,1,0.0,"[band_08, nir, nir_1]",NaN
B8A,B8A,uint16,1,0.0,"[band_8a, nir_narrow, nir_2]",NaN
B09,B09,uint16,1,0.0,"[band_09, water_vapour]",NaN
B11,B11,uint16,1,0.0,"[band_11, swir_1, swir_16]",NaN
B12,B12,uint16,1,0.0,"[band_12, swir_2, swir_22]",NaN
SCL,SCL,uint8,1,0.0,"[mask, qa]","{'qa': {'bits': [0, 1, 2, 3, 4, 5, 6, 7], 'values': {'0': 'no data', '1': 'saturated or defective', '2': 'dark area pixels', '3': 'cloud shadows', '4': 'vegetation', '5': 'bare soils', '6': 'water..."
AOT,AOT,uint16,1,0.0,[aerosol_optical_thickness],NaN
WVP,WVP,uint16,1,0.0,[scene_average_water_vapour],NaN

## Visualising available data
For a more visual way of exploring the data that is available within datacube, we can use the interactive DcViewer utility. We will use the DcViewer utility in this exiercise. Select a product from the drop-down menu on the top-left of the map to show the areas data is available for in blue. You can also use the back and forward buttons above the map to toggle through time.

In [5]:
DcViewer(dc=dc,
        time='2022-01-01',
        center=(29.8,32.3),
        zoom=10)

VBox(children=(HBox(children=(Dropdown(layout=Layout(flex='0 1 auto', width='10em'), options=('gm_s2_annual', …